name: Tests Windows 2019

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_run:
    workflows: ["Pip Package"]
    types: [completed]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tests-src:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip ${{ matrix.python-version }}
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: windows-2019-${{ matrix.python-version }}-pip-pipenv
          restore-keys: |
            windows-2019-${{ matrix.python-version }}-pip-pipenv

      - name: Cache pipenv ${{ matrix.python-version }}
        uses: actions/cache@v2
        with:
          path: ~/.virtualenvs
          key: windows-2019-${{ matrix.python-version }}-pipenv-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            windows-2019-${{ matrix.python-version }}-pipenv-

      # install sphinx using pip on Windows, somehow the pipenv environment doesn't
      # propagate to the command interpreter called from the program.
      - name: Setup pipenv ${{ matrix.python-version }}
        run: python -m pip install --upgrade pipenv

      - name: Install dependencies using pipenv ${{ matrix.python-version }}
        run: |
          python -m pipenv install --dev
          choco install pandoc

      - name: Run Tests ${{ matrix.python-version }}
        run: |
          pipenv run pytest --hypothesis-show-statistics --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov ${{ matrix.python-version }}
        uses: codecov/codecov-action@v1
        if: ${{ always() }}
        with:
          token: ${{ secrets.CODECOV_SECRET }}
          files: ./coverage.xml
          directory: ./coverage/reports/
          # flags: unittest
          env_vars: OS,PYTHON
          name: Windows-Test-Src
          fail_ci_if_error: false
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true

  tests-pkg:
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip ${{ matrix.python-version }}
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: windows-2019-${{ matrix.python-version }}-pip-pipenv
          restore-keys: |
            windows-2019-${{ matrix.python-version }}-pip-pipenv

      - name: Cache pipenv ${{ matrix.python-version }}
        uses: actions/cache@v2
        with:
          path: ~/.virtualenvs
          key: windows-2019-${{ matrix.python-version }}-pipenv-package-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            windows-2019-${{ matrix.python-version }}-pipenv-package-

      - name: Setup pipenv ${{ matrix.python-version }}
        run: python -m pip install --upgrade pipenv

      - name: Install dependencies using pipenv ${{ matrix.python-version }}
        run: |
          python -m pipenv install --dev
          python -m pipenv install obs2org
          python -m pipenv update
          choco install pandoc

      - name: Run Tests ${{ matrix.python-version }}
        run: |
          Remove-Item obs2org -Recurse
          pipenv run pytest --hypothesis-show-statistics --cov=./ --cov-report=xml

      - name: Upload coverage to Codecov ${{ matrix.python-version }}
        uses: codecov/codecov-action@v1
        if: ${{ always() }}
        with:
          token: ${{ secrets.CODECOV_SECRET }}
          files: ./coverage.xml
          directory: ./coverage/reports/
          # flags: unittest
          env_vars: OS,PYTHON
          name: Windows-Test-Pkg
          fail_ci_if_error: false
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
